port = 43212
song-path = "."
# ptsvr-path = /data/local/tmp/server.jar

[phantom]
ip = "auto"
port = "27183"

[[ctrl]]
type = "pause"
key = 119 # KEY_PAUSE

[[ctrl]]
type = "song"
key = 44 # KEY_Z

[screen.unit]
# x1 =
# x2 =
# y =

[screen.solo]
# x1 =
# x2 =
# y =

[screen.2mix]
# x1 = (default = unit.x1)
# x2 = (default = unit.x2)

[screen]
slop = 40

# [[ctrl]]
# key =
# x =
# y =
